In [1]:
import geopandas as gpd
import pandas as pd

In [2]:
collisions = gpd.read_file('collisions_bk.geojson')

In [3]:
collisions.head()

,crash_date,crash_time,borough,zip_code,latitude,longitude,location,on_street_,cross_stre,off_street,...,contribu_2,contribu_3,contribu_4,collision_,vehicle_ty,vehicle__1,vehicle__2,vehicle__3,vehicle__4,geometry
0,2019-01-01,17:07:00,brooklyn,11219.0,40.628220,-74.00522,POINT (-74.00522 40.62822),None,None,1125 65 street,...,None,None,None,4060798,Sedan,None,None,None,None,MULTIPOINT (-74.00522 40.62822)
1,2019-01-01,18:13:00,brooklyn,11219.0,40.635975,-74.00124,POINT (-74.00124 40.635975),54 street,fort hamilton parkway,None,...,None,None,None,4061134,Sedan,None,None,None,None,MULTIPOINT (-74.00124 40.63598)
2,2019-01-01,13:30:00,brooklyn,11214.0,40.614582,-73.99961,POINT (-73.99961 40.614582),None,None,1674 76 street,...,None,None,None,4060514,Sedan,Sedan,None,None,None,MULTIPOINT (-73.99961 40.61458)
3,2019-01-01,15:10:00,brooklyn,11219.0,40.632103,-73.99335,POINT (-73.99335 40.632103),None,None,1350 53 street,...,None,None,None,4062940,Station Wagon/Sport Utility Vehicle,Sedan,None,None,None,MULTIPOINT (-73.99335 40.63210)
4,2019-01-01,06:30:00,brooklyn,11219.0,40.635017,-74.00268,POINT (-74.00268 40.635017),56 street,fort hamilton parkway,None,...,None,None,None,4061126,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,None,None,None,MULTIPOINT (-74.00268 40.63502)

In [6]:
collisions.columns.tolist()

['crash_date',
 'crash_time',
 'borough',
 'zip_code',
 'latitude',
 'longitude',
 'location',
 'on_street_',
 'cross_stre',
 'off_street',
 'number_of_',
 'number_o_1',
 'number_o_2',
 'number_o_3',
 'number_o_4',
 'number_o_5',
 'number_o_6',
 'number_o_7',
 'contributi',
 'contribu_1',
 'contribu_2',
 'contribu_3',
 'contribu_4',
 'collision_',
 'vehicle_ty',
 'vehicle__1',
 'vehicle__2',
 'vehicle__3',
 'vehicle__4',
 'geometry']

In [7]:
collisions = collisions.loc[:,['collision_','geometry']]

In [9]:
collisions.to_file('collision_bk_simplified.geojson',driver='GeoJSON')

In [10]:
lion = gpd.read_file('lion_bk.geojson')

In [11]:
lion.head()

,OBJECTID,Street,SAFStreetN,FeatureTyp,SegmentTyp,IncExFlag,RB_Layer,NonPed,TrafDir,TrafSrc,...,FromLeft,ToLeft,FromRight,ToRight,Join_ID,L_PD_Servi,R_PD_Servi,TRUCK_ROUT,SHAPE_Leng,geometry
0,37380.0,54 STREET,None,0,U,None,B,None,W,DOT,...,1201,1279,1200,1298,3924401000000,None,None,None,685.076847,"MULTILINESTRING ((-73.99723 40.63356, -73.9952..."
1,37381.0,NEW UTRECHT AVENUE,None,0,U,None,B,None,T,DOT,...,5401,5499,0,0,3558801000000,None,None,None,113.012029,"MULTILINESTRING ((-73.99539 40.63188, -73.9954..."
2,37382.0,74 STREET,None,0,U,None,B,None,A,DOT,...,1801,1899,1800,1898,3937201000000,None,None,None,717.618362,"MULTILINESTRING ((-73.99537 40.61400, -73.9933..."
3,37386.0,60 STREET,None,0,U,None,B,None,T,DOT,...,1201,1299,1200,1298,3929201000000,None,None,None,780.024771,"MULTILINESTRING ((-74.00075 40.63018, -73.9985..."
4,37387.0,51 STREET,None,0,U,None,B,None,A,DOT,...,1025,1099,1024,1098,3922801000000,None,None,None,497.674805,"MULTILINESTRING ((-73.99909 40.63742, -73.9976..."

In [12]:
lion = lion[['geometry','OBJECTID','Street']]

In [13]:
lion.to_file('lion_bk_simplified.geojson',driver='GeoJSON')